version: '3.4'
services:
  typesense:
    image: typesense/typesense:0.24.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'